import type { PricingPlan } from "@videoforge/shared";
import { TIER_LIMITS } from "@videoforge/shared";

export const PRICING_PLANS: PricingPlan[] = [
  {
    tier: "free",
    name: "Free",
    monthlyPriceUsd: 0,
    yearlyPriceUsd: 0,
    monthlyPriceInr: 0,
    yearlyPriceInr: 0,
    razorpayPlanIdMonthly: null,
    razorpayPlanIdYearly: null,
    razorpayPlanIdMonthlyInr: null,
    razorpayPlanIdYearlyInr: null,
    highlighted: false,
    features: [
      "3 videos per day",
      "Up to 5 seconds",
      "480p resolution",
      "Watermark included",
      "Basic AI model",
    ],
    limits: TIER_LIMITS.free,
  },
  {
    // Internal tier: "creator" — displayed to India users as "Starter" (₹399/mo)
    tier: "creator",
    name: "Starter",
    monthlyPriceUsd: 19,
    yearlyPriceUsd: 15, // per month billed yearly
    monthlyPriceInr: 399,
    yearlyPriceInr: 319,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_CREATOR_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_CREATOR_YEARLY ?? "",
    razorpayPlanIdMonthlyInr: process.env.RAZORPAY_PLAN_CREATOR_MONTHLY_INR ?? "",
    razorpayPlanIdYearlyInr: process.env.RAZORPAY_PLAN_CREATOR_YEARLY_INR ?? "",
    highlighted: false,
    features: [
      "50 videos per month",
      "Up to 10 seconds per video",
      "Scene-based rendering (3 × 10s scenes)",
      "720p resolution",
      "Draft preview before full render",
      "No watermark",
      "Character consistency",
      "RTX 4090 GPU",
    ],
    limits: TIER_LIMITS.creator,
  },
  {
    // Internal tier: "pro" — displayed to India users as "Creator" (₹799/mo)
    tier: "pro",
    name: "Creator",
    monthlyPriceUsd: 49,
    yearlyPriceUsd: 39,
    monthlyPriceInr: 799,
    yearlyPriceInr: 639,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_PRO_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_PRO_YEARLY ?? "",
    razorpayPlanIdMonthlyInr: process.env.RAZORPAY_PLAN_PRO_MONTHLY_INR ?? "",
    razorpayPlanIdYearlyInr: process.env.RAZORPAY_PLAN_PRO_YEARLY_INR ?? "",
    highlighted: true,
    features: [
      "150 videos per month",
      "Up to 15 seconds per video",
      "Long videos up to 2 minutes",
      "1080p resolution",
      "Draft preview before full render",
      "No watermark",
      "Motion control",
      "Character consistency",
      "Audio-on-video generation",
      "Priority queue",
      "A100 GPU — fastest renders",
      "WAN 2.2 + Kling v2.6 Pro models",
    ],
    limits: TIER_LIMITS.pro,
  },
  {
    // Internal tier: "studio" — displayed to India users as "Pro" (₹1299/mo)
    tier: "studio",
    name: "Pro",
    monthlyPriceUsd: 149,
    yearlyPriceUsd: 119,
    monthlyPriceInr: 1299,
    yearlyPriceInr: 1039,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_STUDIO_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_STUDIO_YEARLY ?? "",
    razorpayPlanIdMonthlyInr: process.env.RAZORPAY_PLAN_STUDIO_MONTHLY_INR ?? "",
    razorpayPlanIdYearlyInr: process.env.RAZORPAY_PLAN_STUDIO_YEARLY_INR ?? "",
    highlighted: false,
    features: [
      "400 videos per month",
      "Up to 30 seconds per video",
      "Long videos up to 2 minutes",
      "1080p resolution",
      "Draft preview before full render",
      "No watermark",
      "Advanced motion control",
      "Character consistency",
      "Audio-on-video generation",
      "Priority queue (fastest)",
      "A100 GPU — dedicated pool",
      "Kling v3 Pro + all models",
      "API access",
      "Dedicated support",
    ],
    limits: TIER_LIMITS.studio,
  },
];
