import type { PricingPlan } from "@videoforge/shared";
import { TIER_LIMITS } from "@videoforge/shared";

export const PRICING_PLANS: PricingPlan[] = [
  {
    tier: "free",
    name: "Free",
    monthlyPriceUsd: 0,
    yearlyPriceUsd: 0,
    razorpayPlanIdMonthly: null,
    razorpayPlanIdYearly: null,
    highlighted: false,
    features: [
      "3 videos per day",
      "Up to 5 seconds",
      "480p resolution",
      "Watermark included",
      "Basic AI model",
    ],
    limits: TIER_LIMITS.free,
  },
  {
    tier: "creator",
    name: "Creator",
    monthlyPriceUsd: 19,
    yearlyPriceUsd: 15, // per month billed yearly
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_CREATOR_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_CREATOR_YEARLY ?? "",
    highlighted: false,
    features: [
      "50 videos per month",
      "Up to 10 seconds",
      "720p resolution",
      "No watermark",
      "Character consistency",
      "WAN 2.2 model access",
    ],
    limits: TIER_LIMITS.creator,
  },
  {
    tier: "pro",
    name: "Pro",
    monthlyPriceUsd: 49,
    yearlyPriceUsd: 39,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_PRO_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_PRO_YEARLY ?? "",
    highlighted: true,
    features: [
      "200 videos per month",
      "Up to 15 seconds",
      "1080p resolution",
      "No watermark",
      "Motion control",
      "Character consistency",
      "Priority queue",
      "Kling v2.6 Pro model",
    ],
    limits: TIER_LIMITS.pro,
  },
  {
    tier: "studio",
    name: "Studio",
    monthlyPriceUsd: 149,
    yearlyPriceUsd: 119,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_STUDIO_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_STUDIO_YEARLY ?? "",
    highlighted: false,
    features: [
      "Unlimited videos",
      "Up to 15 seconds",
      "1080p resolution",
      "No watermark",
      "Advanced motion control",
      "Character consistency",
      "Priority queue",
      "Kling v3 Pro (latest model)",
      "API access",
      "Dedicated support",
    ],
    limits: TIER_LIMITS.studio,
  },
];
