import type { PricingPlan } from "@videoforge/shared";
import { TIER_LIMITS } from "@videoforge/shared";

export const PRICING_PLANS: PricingPlan[] = [
  {
    tier: "free",
    name: "Free",
    monthlyPriceUsd: 0,
    yearlyPriceUsd: 0,
    monthlyPriceInr: 0,
    yearlyPriceInr: 0,
    razorpayPlanIdMonthly: null,
    razorpayPlanIdYearly: null,
    razorpayPlanIdMonthlyInr: null,
    razorpayPlanIdYearlyInr: null,
    highlighted: false,
    features: [
      "3 videos per day",
      "Up to 5 seconds",
      "480p resolution",
      "Watermark included",
      "Basic AI model",
    ],
    limits: TIER_LIMITS.free,
  },
  {
    tier: "creator",
    name: "Creator",
    monthlyPriceUsd: 19,
    yearlyPriceUsd: 15, // per month billed yearly
    monthlyPriceInr: 799,
    yearlyPriceInr: 599,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_CREATOR_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_CREATOR_YEARLY ?? "",
    razorpayPlanIdMonthlyInr: process.env.RAZORPAY_PLAN_CREATOR_MONTHLY_INR ?? "",
    razorpayPlanIdYearlyInr: process.env.RAZORPAY_PLAN_CREATOR_YEARLY_INR ?? "",
    highlighted: false,
    features: [
      "50 videos per month",
      "Up to 10 seconds (short clips)",
      "Long videos up to 60 seconds",
      "720p resolution",
      "No watermark",
      "Character consistency",
      "Audio-on-video generation",
      "WAN 2.2 model access",
    ],
    limits: TIER_LIMITS.creator,
  },
  {
    tier: "pro",
    name: "Pro",
    monthlyPriceUsd: 49,
    yearlyPriceUsd: 39,
    monthlyPriceInr: 1999,
    yearlyPriceInr: 1599,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_PRO_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_PRO_YEARLY ?? "",
    razorpayPlanIdMonthlyInr: process.env.RAZORPAY_PLAN_PRO_MONTHLY_INR ?? "",
    razorpayPlanIdYearlyInr: process.env.RAZORPAY_PLAN_PRO_YEARLY_INR ?? "",
    highlighted: true,
    features: [
      "200 videos per month",
      "Up to 15 seconds (short clips)",
      "Long videos up to 2 minutes",
      "1080p resolution",
      "No watermark",
      "Motion control",
      "Character consistency",
      "Audio-on-video generation",
      "Priority queue",
      "Kling v2.6 Pro model",
      "LTXV 13B & Longcat 720p long-video models",
    ],
    limits: TIER_LIMITS.pro,
  },
  {
    tier: "studio",
    name: "Studio",
    monthlyPriceUsd: 149,
    yearlyPriceUsd: 119,
    monthlyPriceInr: 5999,
    yearlyPriceInr: 4999,
    razorpayPlanIdMonthly: process.env.RAZORPAY_PLAN_STUDIO_MONTHLY ?? "",
    razorpayPlanIdYearly: process.env.RAZORPAY_PLAN_STUDIO_YEARLY ?? "",
    razorpayPlanIdMonthlyInr: process.env.RAZORPAY_PLAN_STUDIO_MONTHLY_INR ?? "",
    razorpayPlanIdYearlyInr: process.env.RAZORPAY_PLAN_STUDIO_YEARLY_INR ?? "",
    highlighted: false,
    features: [
      "Unlimited videos",
      "Up to 15 seconds (short clips)",
      "Long videos up to 2 minutes",
      "1080p resolution",
      "No watermark",
      "Advanced motion control",
      "Character consistency",
      "Audio-on-video generation",
      "Priority queue",
      "Kling v3 Pro (latest model)",
      "All long-video models including Krea WAN 14B",
      "API access",
      "Dedicated support",
    ],
    limits: TIER_LIMITS.studio,
  },
];
